### ISSUE TITLE
Outdated links to Github source files on AXI Tutorials

### ISSUE THREAD

**Issue by alemuller** [ZipCPU/website#3]
There are a few links on the blog that point out to, what I suppose, was a previous project organization. You can find them looking for:
```
https://github.com/ZipCPU/wb2axip/blob/master/*.v
```

Nowadays they are at:
```
https://github.com/ZipCPU/wb2axip/blob/master/rtl/*.v
```

**Comment by ZipCPU** [comment]
Thank you.  It looks like my automatic link catcher didn't find these.  I found several in the AXI-full article.  These have now been fixed.

Dan
