### ISSUE TITLE
A small typo/mistake.

### ISSUE THREAD

**Issue by hakan-demirli** [ZipCPU/website#7]
Both statements are the same.
![sby or not sby](https://zipcpu.com/img/sby-taskcmd.svg)

**Reference:**
https://github.com/YosysHQ/sby/blob/4adb99ea303cfe015469be18613b2ce6fbd816fd/docs/source/reference.rst?plain=1#L59

```The tag ``~<taskname>:`` can be used for a line or block that should not be used when...```

**The blog post:**
https://github.com/ZipCPU/website/blob/master/img/sby-taskcmd.svg
https://zipcpu.com/zipcpu/2018/12/20/sby-makefile.html

BTW, thanks for the blog posts they are awesome.

**Comment by ZipCPU** [comment]
This is now fixed.

An unfortunate consequence is that the above image in the issue page no longer supports your description.  Still, the bug has been addressed.

Thank you for reporting, and please accept my apologies for taking so long!

Dan
