### ISSUE TITLE
Beginners Tutorial: Verilator driver compilation failure

### ISSUE THREAD

**Issue by fm4dd** [ZipCPU/website#8]
Hi Daniel,

In [https://zipcpu.com/tutorial/lsn-01-wires.pdf](https://zipcpu.com/tutorial/lsn-01-wires.pdf) on page 24, the g++ compilation step in example **ex-01-thruwire** fails for me with below link error:

```
$ make
Building a Verilator-based simulation of thruwire
g++ -I/usr/share/verilator/include  -I obj_dir     \
	/usr/share/verilator/include/verilated.cpp \
	thruwire.cpp obj_dir/Vthruwire__ALL.a      \
	-o thruwire
/usr/bin/ld: /tmp/ccZsNn1l.o: in function `VerilatedContext::threadPoolp()':
verilated.cpp:(.text+0xbd8e): undefined reference to `VlThreadPool::VlThreadPool(VerilatedContext*, unsigned int)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:44: thruwire] Error 1
```

Do I miss any environment setting? The very same error happens when I try the make in example **ex-01-maskbus**. My system is a standard Debian 12 Linux, and comes with verilator version 5.006:
```
$ verilator -V
Verilator 5.006 2023-01-22 rev (Debian 5.006-3)

Copyright 2003-2023 by Wilson Snyder.  Verilator is free software; you can
redistribute it and/or modify the Verilator internals under the terms of
either the GNU Lesser General Public License Version 3 or the Perl Artistic
License Version 2.0.

See https://verilator.org for documentation

Summary of configuration:
  Compiled in defaults if not in environment:
    SYSTEMC            = 
    SYSTEMC_ARCH       = 
    SYSTEMC_INCLUDE    = 
    SYSTEMC_LIBDIR     = 
    VERILATOR_ROOT     = /usr/share/verilator
    SystemC system-wide = 1

Environment:
    MAKE               = 
    PERL               = 
    SYSTEMC            = 
    SYSTEMC_ARCH       = 
    SYSTEMC_INCLUDE    = 
    SYSTEMC_LIBDIR     = 
    VERILATOR_BIN      = 
    VERILATOR_ROOT     = 

Supported features (compiled-in or forced by environment):
    COROUTINES         = 1
    SYSTEMC            = 1
```

**Comment by fm4dd** [comment]
I found the 'all-in-one' command from the [Verilator example C++ execution](https://veripool.org/guide/latest/example_cc.html#example-c-execution) page works:
```
$ verilator --cc --exe --build -j 0 -Wall thruwire.cpp thruwire.v
make: Entering directory '/mnt/hgfs/fpga/projects/gatemate/gt-beginners/ex-01-thruwire/obj_dir'
...
Archive ar -rcs Vthruwire__ALL.a Vthruwire__ALL.o
g++    thruwire.o verilated.o verilated_threads.o Vthruwire__ALL.a    -pthread -lpthread -latomic   -o Vthruwire
```
It leaves a turnkey obj_dir/Vthruwire binary file that I can run:
```
$ obj_dir/Vthruwire
k =  0, sw = 0, led = 0
k =  1, sw = 1, led = 1
k =  2, sw = 0, led = 0
k =  3, sw = 1, led = 1
k =  4, sw = 0, led = 0
k =  5, sw = 1, led = 1
...
```

Is there any reason for the intermediate step of building the shared object in slide 19? It seems to be no longer needed.

**Comment by ZipCPU** [comment]
I think if you use the -exe argument you don't need the extra step.  On the other hand, it will make it more difficult to integrate C++ models and test drivers into your design at the next step.

Dan

**Comment by fm4dd** [comment]
Hi Dan,

Thank you for responding. Once I find how to fix the missing `VlThreadPool::VlThreadPool' reference, I'll share it here. So far I continued with the --exe argument for simplicity (adding -o ../module for creating the simulation binary into the top folder) through Lesson 2.

I also want to use this chance to send a big "Thank You" for publishing the tutorial. A lot of work went into it, and the comments on common pitfalls are very valuable. Formal verification and design testing is not commonly part of basic training. I noticed your start on the 'advanced' tutorial, and I wish you much success and energy for it, the topics are great.

Cheers, Frank

**Comment by fm4dd** [comment]
Its resolved. The g++ command needs the addition of /usr/share/verilator/include/verilated_threads.cpp.

For completeness, the full commandline is below, and a reference screenshot attached. 
Closing the issue. Thank You!

```
$ g++ -I /usr/share/verilator/include -I obj_dir/ /usr/share/verilator/include/verilated.cpp thruwire.cpp /usr/share/verilator/include/verilated_threads.cpp obj_dir/Vthruwire__ALL.a -o thruwire
```
![20230719 verilator compilation success](https://github.com/ZipCPU/website/assets/1367011/64496066-c273-43e5-a100-8bda2257bc7a)

**Comment by ZipCPU** [comment]
Thank you!
